/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import model.DBModel;
import model.IModel;

/**
 *
 * @author nagyg
 */
public class Foablak extends javax.swing.JFrame {

    private IModel model;

    public Foablak() {
        initComponents();

        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                sajatClose();
            }
        });
        setLocationRelativeTo(null);
        setTitle("Könyvtári tagok és könyvek nyílvántartása");

        String dbUser = "root";
        String dbPass = "1234";
        String dbURL = "jdbc:mysql://localhost:3306/konyvtar";
        
        try {
            Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPass);
            model = new DBModel(conn);
            
        } catch (SQLException ex) {
            hibaAblak(ex.toString());
        }
        
    }

    public static void hibaAblak(String hiba) {
        JOptionPane.showMessageDialog(null, hiba, "Hiba történt",
                JOptionPane.ERROR_MESSAGE);
    }

    public void sajatClose() {
        if (model != null) {
            try {
                model.close();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.toString(), "Adatbázis hiba",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mbFajl = new javax.swing.JMenu();
        miKolcsonzes = new javax.swing.JMenuItem();
        miVisszavet = new javax.swing.JMenuItem();
        miKilepes = new javax.swing.JMenuItem();
        mbAdatok = new javax.swing.JMenu();
        miTagok = new javax.swing.JMenuItem();
        miKonyvek = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        mbFajl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mbFajl.setForeground(new java.awt.Color(102, 102, 102));
        mbFajl.setText("Fájl");
        mbFajl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mbFajl.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        mbFajl.setMargin(new java.awt.Insets(5, 5, 5, 5));

        miKolcsonzes.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        miKolcsonzes.setForeground(new java.awt.Color(102, 102, 102));
        miKolcsonzes.setText("Kölcsönzés");
        miKolcsonzes.setMargin(new java.awt.Insets(5, 5, 5, 5));
        miKolcsonzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKolcsonzesActionPerformed(evt);
            }
        });
        mbFajl.add(miKolcsonzes);

        miVisszavet.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        miVisszavet.setForeground(new java.awt.Color(102, 102, 102));
        miVisszavet.setText("Visszavét");
        miVisszavet.setMargin(new java.awt.Insets(5, 5, 5, 5));
        miVisszavet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisszavetActionPerformed(evt);
            }
        });
        mbFajl.add(miVisszavet);

        miKilepes.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        miKilepes.setForeground(new java.awt.Color(102, 102, 102));
        miKilepes.setText("Kilépés");
        miKilepes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        miKilepes.setMargin(new java.awt.Insets(5, 5, 5, 5));
        miKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKilepesActionPerformed(evt);
            }
        });
        mbFajl.add(miKilepes);

        jMenuBar1.add(mbFajl);

        mbAdatok.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mbAdatok.setForeground(new java.awt.Color(102, 102, 102));
        mbAdatok.setText("Adatok");
        mbAdatok.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mbAdatok.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        mbAdatok.setMargin(new java.awt.Insets(5, 5, 5, 5));

        miTagok.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        miTagok.setForeground(new java.awt.Color(102, 102, 102));
        miTagok.setText("Tagok");
        miTagok.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        miTagok.setMargin(new java.awt.Insets(5, 5, 5, 5));
        miTagok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTagokActionPerformed(evt);
            }
        });
        mbAdatok.add(miTagok);

        miKonyvek.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        miKonyvek.setForeground(new java.awt.Color(102, 102, 102));
        miKonyvek.setText("Könyvek");
        miKonyvek.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        miKonyvek.setMargin(new java.awt.Insets(5, 5, 5, 5));
        miKonyvek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKonyvekActionPerformed(evt);
            }
        });
        mbAdatok.add(miKonyvek);

        jMenuBar1.add(mbAdatok);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 881, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKilepesActionPerformed
         sajatClose();
    }//GEN-LAST:event_miKilepesActionPerformed

    private void miTagokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTagokActionPerformed
        TagokDialog td = new TagokDialog(this, true, model);
        td.setVisible(true);
    }//GEN-LAST:event_miTagokActionPerformed

    private void miKonyvekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKonyvekActionPerformed
       KonyvekDialog kd = new KonyvekDialog(this, true, model);
       kd.setVisible(true);
    }//GEN-LAST:event_miKonyvekActionPerformed

    private void miKolcsonzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKolcsonzesActionPerformed
        KolcsonzesDialog klcsd = new KolcsonzesDialog(this, true, model);
        klcsd.setVisible(true);
    }//GEN-LAST:event_miKolcsonzesActionPerformed

    private void miVisszavetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisszavetActionPerformed
        VisszavetDialog vd = new VisszavetDialog(this, true, model);
        vd.setVisible(true);
        
    }//GEN-LAST:event_miVisszavetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mbAdatok;
    private javax.swing.JMenu mbFajl;
    private javax.swing.JMenuItem miKilepes;
    private javax.swing.JMenuItem miKolcsonzes;
    private javax.swing.JMenuItem miKonyvek;
    private javax.swing.JMenuItem miTagok;
    private javax.swing.JMenuItem miVisszavet;
    // End of variables declaration//GEN-END:variables
}
