package gui;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.IModel;
import model.Konyv;
import model.Tag;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nagyg
 */
public class KolcsonzesDialog extends javax.swing.JDialog {

    private java.awt.Frame parent;
    private IModel model;
    private List<Tag> tagok;
    private List<Konyv> konyvek;
    private DefaultTableModel dtm;

    public KolcsonzesDialog(java.awt.Frame parent, boolean modal, IModel model) {
        super(parent, modal);
        initComponents();

        this.parent = parent;
        this.model = model;

        dtm = (DefaultTableModel) tblKolcsonozhetoKonyvek.getModel();

        setLocationRelativeTo(parent);
        setTitle("Könyvek kikölcsönzése");

        try {
            Tag t = model.getTagByID(0);
            tagok = model.getAllTag();
            cbTag.setModel(new DefaultComboBoxModel(tagok.toArray()));
            konyvek = model.getAllKonyv(t);

            tablaFrissit();
        } catch (SQLException ex) {
            Foablak.hibaAblak(ex.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTag = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKolcsonozhetoKonyvek = new javax.swing.JTable();
        btnKolcsonzes = new javax.swing.JButton();
        btnMegsem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbTag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblKolcsonozhetoKonyvek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblKolcsonozhetoKonyvek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Szerző", "Cím", "Oldalszám"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblKolcsonozhetoKonyvek);

        btnKolcsonzes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKolcsonzes.setText("Kölcsönzés");
        btnKolcsonzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKolcsonzesActionPerformed(evt);
            }
        });

        btnMegsem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMegsem.setText("Mégsem");
        btnMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegsemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbTag, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMegsem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKolcsonzes))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnKolcsonzes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnMegsem, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbTag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnKolcsonzes, btnMegsem});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegsemActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnMegsemActionPerformed

    private void btnKolcsonzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKolcsonzesActionPerformed
        Tag t = (Tag) cbTag.getSelectedItem();
        int sor = tblKolcsonozhetoKonyvek.getSelectedRow();

        if (sor > -1) {
            try {
                Konyv kivalasztott = konyvek.get(sor);
                kivalasztott.setTagId(t.getId());

                model.updateKonyv(kivalasztott);

                tablaFrissit();
                setVisible(false);
            } catch (SQLException ex) {
                Foablak.hibaAblak(ex.toString());
            }
        } else {
            Foablak.hibaAblak("Válasszon ki egy sort a kölcsönzéshez");
        }

    }//GEN-LAST:event_btnKolcsonzesActionPerformed
    private void tablaFrissit() {
        dtm.getDataVector().clear();
        dtm.fireTableDataChanged();
        for (Konyv k : konyvek) {
            Vector sor = new Vector();
            Tag tag;

            try {
                tag = model.getTagByID(k.getTagId());

                if (tag != null) {
                    sor.add(tag.getNev());
                } else {
                    sor.add("Nincs ilyen tag");
                }
                sor.add(k.getSzerzo());
                sor.add(k.getCim());
                sor.add(k.getOldalszam());
                dtm.addRow(sor);
            } catch (SQLException ex) {
                Foablak.hibaAblak(ex.toString());
            }
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKolcsonzes;
    private javax.swing.JButton btnMegsem;
    private javax.swing.JComboBox cbTag;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKolcsonozhetoKonyvek;
    // End of variables declaration//GEN-END:variables
}
