/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import model.Konyv;
import model.Tag;

/**
 *
 * @author nagyg
 */
public class KonyvAdatokDialog extends javax.swing.JDialog {

    private java.awt.Frame parent;
    private boolean mentes;
    private Konyv konyv;

    public KonyvAdatokDialog(java.awt.Frame parent, List<Tag> tagok, Tag kivalasztott) {
        super(parent, true);
        initComponents();
        this.parent = parent;

        mentes = false;
        cbTag.setModel(new DefaultComboBoxModel(tagok.toArray(new Tag[0])));
        cbTag.setSelectedItem(kivalasztott);
        setLocationRelativeTo(parent);
        if (kivalasztott == null) {
            setTitle("Új könyv felvétele");
        } 
    }

    public Konyv getKonyv() {
        return konyv;
    }

    public boolean isMentes() {
        return mentes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTag = new javax.swing.JLabel();
        lbSzerzo = new javax.swing.JLabel();
        lbCim = new javax.swing.JLabel();
        lbOldalszam = new javax.swing.JLabel();
        cbTag = new javax.swing.JComboBox<>();
        tfSzerzo = new javax.swing.JTextField();
        tfCim = new javax.swing.JTextField();
        tfOldalszam = new javax.swing.JTextField();
        btnMentes = new javax.swing.JButton();
        btnMegsem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTag.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTag.setText("Tag:");

        lbSzerzo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSzerzo.setText("Szerző:");

        lbCim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbCim.setText("Cím:");

        lbOldalszam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbOldalszam.setText("Oldalszám:");

        cbTag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfSzerzo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfCim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfOldalszam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnMentes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMentes.setText("Mentés");
        btnMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMentesActionPerformed(evt);
            }
        });

        btnMegsem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMegsem.setText("Mégsem");
        btnMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegsemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMegsem)
                        .addGap(52, 52, 52)
                        .addComponent(btnMentes, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbOldalszam)
                                .addComponent(lbCim)
                                .addComponent(lbTag, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lbSzerzo))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbTag, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfCim, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(tfSzerzo))
                            .addComponent(tfOldalszam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbCim, lbOldalszam, lbSzerzo, lbTag});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMegsem, btnMentes});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTag)
                    .addComponent(cbTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSzerzo)
                    .addComponent(tfSzerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCim)
                    .addComponent(tfCim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOldalszam)
                    .addComponent(tfOldalszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMentes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMegsem))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMegsem, btnMentes});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegsemActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnMegsemActionPerformed

    private void btnMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMentesActionPerformed
        Tag t = (Tag) cbTag.getSelectedItem();
        if (t != null) {
            try {
                konyv = new Konyv();

                konyv.setSzerzo(tfSzerzo.getText());
                konyv.setCim(tfCim.getText());
                konyv.setOldalszam(Integer.parseInt(tfOldalszam.getText()));
                konyv.setTagId(t.getId());

                mentes = true;
                setVisible(false);
            } catch (NumberFormatException ex) {
                Foablak.hibaAblak("Kérlek csak egész számot adj meg!");
            }
        } else {
            Foablak.hibaAblak("Kötelező tagot választani");
        }


    }//GEN-LAST:event_btnMentesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMegsem;
    private javax.swing.JButton btnMentes;
    private javax.swing.JComboBox<Tag> cbTag;
    private javax.swing.JLabel lbCim;
    private javax.swing.JLabel lbOldalszam;
    private javax.swing.JLabel lbSzerzo;
    private javax.swing.JLabel lbTag;
    private javax.swing.JTextField tfCim;
    private javax.swing.JTextField tfOldalszam;
    private javax.swing.JTextField tfSzerzo;
    // End of variables declaration//GEN-END:variables
}
