/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.Konyv;
import model.Tag;

/**
 *
 * @author nagyg
 */
public class KonyvAdatokModositDialog extends javax.swing.JDialog {

    private java.awt.Frame parent;
    private boolean mentes;
    private Konyv kivalasztott;

    public KonyvAdatokModositDialog(java.awt.Frame parent, boolean modal, Konyv kivalasztott) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.kivalasztott = kivalasztott;
        mentes = false;
        setLocationRelativeTo(parent);
        if (kivalasztott != null) {
            setTitle("Könyv adatainak módosítása");
            System.out.println(kivalasztott);
            tfSzerzo.setText(kivalasztott.getSzerzo());
            tfCim.setText(kivalasztott.getCim());
            tfOldalszam.setText(String.valueOf(kivalasztott.getOldalszam()));
        }
    }

    public Konyv getKonyv() {
        return kivalasztott;
    }

    public boolean isMentes() {
        return mentes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSzerzo = new javax.swing.JLabel();
        lbCim = new javax.swing.JLabel();
        lbOldalszam = new javax.swing.JLabel();
        tfSzerzo = new javax.swing.JTextField();
        tfCim = new javax.swing.JTextField();
        tfOldalszam = new javax.swing.JTextField();
        btnMegsem = new javax.swing.JButton();
        btnMentes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbSzerzo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSzerzo.setText("Szerző:");

        lbCim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbCim.setText("Cím:");

        lbOldalszam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbOldalszam.setText("Oldalszám:");

        tfSzerzo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfCim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfOldalszam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnMegsem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMegsem.setText("Mégsem");
        btnMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegsemActionPerformed(evt);
            }
        });

        btnMentes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMentes.setText("Mentés");
        btnMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbSzerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbCim, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbOldalszam)
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSzerzo, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addComponent(tfCim)
                            .addComponent(tfOldalszam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMegsem)
                        .addGap(73, 73, 73)
                        .addComponent(btnMentes)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lbSzerzo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tfSzerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCim)
                    .addComponent(tfCim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOldalszam)
                    .addComponent(tfOldalszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMegsem)
                    .addComponent(btnMentes))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegsemActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnMegsemActionPerformed

    private void btnMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMentesActionPerformed

        try {
            //kivalasztott = new Konyv();

            kivalasztott.setSzerzo(tfSzerzo.getText());
            kivalasztott.setCim(tfCim.getText());
            kivalasztott.setOldalszam(Integer.parseInt(tfOldalszam.getText()));

            mentes = true;
            setVisible(false);
        } catch (NumberFormatException ex) {
            Foablak.hibaAblak("Kérlek csak egész számot adj meg!");
        }
    }//GEN-LAST:event_btnMentesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMegsem;
    private javax.swing.JButton btnMentes;
    private javax.swing.JLabel lbCim;
    private javax.swing.JLabel lbOldalszam;
    private javax.swing.JLabel lbSzerzo;
    private javax.swing.JTextField tfCim;
    private javax.swing.JTextField tfOldalszam;
    private javax.swing.JTextField tfSzerzo;
    // End of variables declaration//GEN-END:variables
}
