/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JButton;
import model.Tag;

/**
 *
 * @author nagyg
 */
public class TagAdatokDialog extends javax.swing.JDialog {

    private Tag tag;
    private boolean mentes;

    
    
    public TagAdatokDialog(java.awt.Frame parent, boolean modal, Tag tag) {
        super(parent, modal);
        initComponents();
        mentes = false;
        this.tag = tag;
        
        setLocationRelativeTo(parent);
        if(tag == null){
            setTitle("Új tag felvétele");
        }else{
            setTitle("Tag adatainak módosítása");
            tfNev.setText(tag.getNev());
            tfEmail.setText(tag.getEmail());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNev = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        tfNev = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        btnMegsem = new javax.swing.JButton();
        btnMentes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbNev.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lbNev.setText("Név:");

        lbEmail.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lbEmail.setText("Email:");

        tfNev.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N

        tfEmail.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N

        btnMegsem.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btnMegsem.setText("Mégsem");
        btnMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegsemActionPerformed(evt);
            }
        });

        btnMentes.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btnMentes.setText("Mentés");
        btnMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMegsem)
                        .addGap(56, 56, 56)
                        .addComponent(btnMentes))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(lbNev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNev, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addComponent(tfEmail))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNev)
                    .addComponent(tfNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMegsem)
                    .addComponent(btnMentes))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegsemActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnMegsemActionPerformed

    private void btnMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMentesActionPerformed
        if(tag == null){
            tag = new Tag();
        }
        tag.setNev(tfNev.getText());
        tag.setEmail(tfEmail.getText());
        mentes = true;
        setVisible(false);
    }//GEN-LAST:event_btnMentesActionPerformed

    /**
     * @param args the command line arguments
     */
  public Tag getTag() {
        return tag;
    }

    public boolean isMentes() {
        return mentes;
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMegsem;
    private javax.swing.JButton btnMentes;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbNev;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNev;
    // End of variables declaration//GEN-END:variables
}
