/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.IModel;
import model.Tag;

/**
 *
 * @author nagyg
 */
public class TagokDialog extends javax.swing.JDialog {

    private java.awt.Frame parent;
    private IModel model;
    private List<Tag> tagok;

    public TagokDialog(java.awt.Frame parent, boolean modal, IModel model) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.model = model;

        setLocationRelativeTo(parent);
        setTitle("Tagok nyílvántartása");

        listaFrissit();
    }

    public void listaFrissit() {
        try {
            tagok = model.getAllTag();
            lstTagok.setListData(tagok.toArray(new Tag[]{}));
        } catch (SQLException ex) {
            Foablak.hibaAblak(ex.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstTagok = new javax.swing.JList<>();
        btnUj = new javax.swing.JButton();
        btnModosit = new javax.swing.JButton();
        btnTorol = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstTagok.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16)); // NOI18N
        lstTagok.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstTagok);

        btnUj.setFont(new java.awt.Font("Monospac821 BT", 1, 20)); // NOI18N
        btnUj.setText("Új");
        btnUj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjActionPerformed(evt);
            }
        });

        btnModosit.setFont(new java.awt.Font("Monospac821 BT", 1, 20)); // NOI18N
        btnModosit.setText("Módosít");
        btnModosit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModositActionPerformed(evt);
            }
        });

        btnTorol.setFont(new java.awt.Font("Monospac821 BT", 1, 20)); // NOI18N
        btnTorol.setText("Töröl");
        btnTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTorolActionPerformed(evt);
            }
        });

        btnOk.setFont(new java.awt.Font("Monospac821 BT", 1, 20)); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUj)
                    .addComponent(btnModosit)
                    .addComponent(btnTorol)
                    .addComponent(btnOk))
                .addGap(30, 30, 30))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnModosit, btnOk, btnTorol, btnUj});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUj)
                        .addGap(18, 18, 18)
                        .addComponent(btnModosit)
                        .addGap(18, 18, 18)
                        .addComponent(btnTorol)
                        .addGap(247, 247, 247)
                        .addComponent(btnOk)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjActionPerformed
        TagAdatokDialog tad = new TagAdatokDialog(parent, true, null);
        tad.setVisible(true);

        if (tad.isMentes()) {
            Tag tag = tad.getTag();
            try {
                model.addTag(tag);
                listaFrissit();
            } catch (SQLException ex) {
                Foablak.hibaAblak(ex.toString());
            }
        }
    }//GEN-LAST:event_btnUjActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnModositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModositActionPerformed
        Tag kivalasztott = lstTagok.getSelectedValue();
        if (kivalasztott != null) {
            TagAdatokDialog tad = new TagAdatokDialog(parent, true, kivalasztott);
            tad.setVisible(true);

            if (tad.isMentes()) {
                try {
                    model.updateTag(kivalasztott);
                    listaFrissit();
                } catch (SQLException ex) {
                    Foablak.hibaAblak(ex.toString());
                }
            }

        } else {
            Foablak.hibaAblak("A módosításhoz válasszon ki egy tagot!");
        }
    }//GEN-LAST:event_btnModositActionPerformed

    private void btnTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTorolActionPerformed
        Tag torolni = lstTagok.getSelectedValue();
        Object[] options = {"Igen", "Nem"};
        if (torolni != null) {
            int valasz = JOptionPane.showOptionDialog(parent, "Biztosan törölni akarod?", "Biztos",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            if (valasz == JOptionPane.YES_OPTION) {
                try {
                    if(model.getAllKonyv(torolni).isEmpty()){//nincs hozzá tartozó kivett könyv, tehát törölhető
                        model.removeTag(torolni);
                        listaFrissit();//frissíti a listát törlés után
                    }else{
                        Foablak.hibaAblak("Ennél a tagnál van kikölcsönzött könyv, ezért nem törölhető");
                    }
                } catch (SQLException ex) {
                    Foablak.hibaAblak(ex.toString());
                }
            }
        } else {
            Foablak.hibaAblak("A törléshez válassz ki egy tagot");
        }


    }//GEN-LAST:event_btnTorolActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModosit;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnTorol;
    private javax.swing.JButton btnUj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Tag> lstTagok;
    // End of variables declaration//GEN-END:variables
}
