/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.IModel;
import model.Konyv;
import model.Tag;

/**
 *
 * @author nagyg
 */
public class VisszavetDialog extends javax.swing.JDialog {

    private java.awt.Frame parent;
    private IModel model;
    private List<Tag> tagok;
    private List<Konyv> konyvek;
    private DefaultTableModel dtm;

    public VisszavetDialog(java.awt.Frame parent, boolean modal, IModel model) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.model = model;

        dtm = (DefaultTableModel) tblVisszavet.getModel();
        setLocationRelativeTo(parent);
        setTitle("Könyvek visszavétele");

        try {

            tagok = model.getAllTag();
            cbTag.setModel(new DefaultComboBoxModel(tagok.toArray()));

            
        } catch (SQLException ex) {
            Foablak.hibaAblak(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTag = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisszavet = new javax.swing.JTable();
        btnVisszavet = new javax.swing.JButton();
        btnMegsem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbTag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbTag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTagActionPerformed(evt);
            }
        });

        tblVisszavet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblVisszavet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Szerző", "Cím", "Oldalszám"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVisszavet);

        btnVisszavet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVisszavet.setText("Visszavét");
        btnVisszavet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisszavetActionPerformed(evt);
            }
        });

        btnMegsem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMegsem.setText("Mégsem");
        btnMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegsemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbTag, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMegsem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisszavet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTag, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnVisszavet, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMegsem, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegsemActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnMegsemActionPerformed

    private void cbTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTagActionPerformed
        Tag kivalasztott = (Tag) cbTag.getSelectedItem(); 
        if (kivalasztott != null) {
            try {
                konyvek = model.getAllKonyv(kivalasztott); 
                tablaFrissit(); 

            } catch (SQLException ex) {
                Foablak.hibaAblak(ex.toString());
            }
        }
    }//GEN-LAST:event_cbTagActionPerformed

    private void btnVisszavetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisszavetActionPerformed
        
        int sor = tblVisszavet.getSelectedRow();
        if(sor>0){
            try {
            Konyv kivalasztott = konyvek.get(sor);
            kivalasztott.setTagId(0);
             model.updateKonyv(kivalasztott);
                tablaFrissit();
                setVisible(false);
                } catch (SQLException ex) {
                Foablak.hibaAblak(ex.toString());
            }
        } else {
            Foablak.hibaAblak("Válasszon ki egy sort a visszavéthez");
        }
        
        
        
        
    }//GEN-LAST:event_btnVisszavetActionPerformed
    private void tablaFrissit() {
        dtm.getDataVector().clear();
        dtm.fireTableDataChanged();
        for (Konyv k : konyvek) {
            Vector sor = new Vector();
            Tag tag;

            try {
                tag = model.getTagByID(k.getTagId());

                if (tag != null) {
                    sor.add(tag.getNev());
                } else {
                    sor.add("Nincs ilyen tag");
                }
                sor.add(k.getSzerzo());
                sor.add(k.getCim());
                sor.add(k.getOldalszam());
                dtm.addRow(sor);
            } catch (SQLException ex) {
                Foablak.hibaAblak(ex.toString());
            }
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMegsem;
    private javax.swing.JButton btnVisszavet;
    private javax.swing.JComboBox cbTag;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVisszavet;
    // End of variables declaration//GEN-END:variables
}
